site_name: Wanchufley's Portfolio 
site_url: https://sitename.example
theme:
  name: material
  palette: 
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: black
      accent: deep purple
     # Dark mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark Mode
      primary: black
      accent: deep purple
  features:
    - navigation.sections
#    - navigation.expand
    - navigation.footer
    - content.tooltips
  icon:
    logo: fontawesome/solid/w
    

nav:
  - ğŸ  Home: index.md
  - ğŸ‘¤ About: about.md
  - ğŸ“’ Blog:
        - ğŸ”§ Ufw-role: posts/post-02-ufw-role
        - ğŸ’¾ Dotfiles Setup: posts/post-03-dotfile-mgmnt
        - ğŸ¤– Figurine Setup: posts/post-01-figurine-install
#  - ğŸ¤ Sponsor: sponsor.md

plugins:
  - search
#  - blog:
#      blog_dir: .
#      categories_allowed:
#      - Tech
#      post_url_format: "{slug}"
#      blog_toc: true
#      archive: false
#      index_page: false
  - tags:
      tags_file: tags.md
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.tabbed:
     alternate_style: true
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.tilde
